// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLaiqe_QbKDW2Cv6xvz4lYyguq7mUQCqE',
    appId: '1:839431369002:web:ddb49b90ddf0123b08ee53',
    messagingSenderId: '839431369002',
    projectId: 'employeetasktracking',
    authDomain: 'employeetasktracking.firebaseapp.com',
    storageBucket: 'employeetasktracking.firebasestorage.app',
    measurementId: 'G-ZJPN0BDD5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIW90MZp2BsutL9IuQ9HqfXqW_poFQVEY',
    appId: '1:839431369002:android:8279efe1e34f5a8008ee53',
    messagingSenderId: '839431369002',
    projectId: 'employeetasktracking',
    storageBucket: 'employeetasktracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYSfZw7cQX92oD-nYcHJo0QWAx7KHP80I',
    appId: '1:839431369002:ios:53ec52197d583b7208ee53',
    messagingSenderId: '839431369002',
    projectId: 'employeetasktracking',
    storageBucket: 'employeetasktracking.firebasestorage.app',
    iosBundleId: 'com.example.employeeTaskTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYSfZw7cQX92oD-nYcHJo0QWAx7KHP80I',
    appId: '1:839431369002:ios:53ec52197d583b7208ee53',
    messagingSenderId: '839431369002',
    projectId: 'employeetasktracking',
    storageBucket: 'employeetasktracking.firebasestorage.app',
    iosBundleId: 'com.example.employeeTaskTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLaiqe_QbKDW2Cv6xvz4lYyguq7mUQCqE',
    appId: '1:839431369002:web:63287ad47145201008ee53',
    messagingSenderId: '839431369002',
    projectId: 'employeetasktracking',
    authDomain: 'employeetasktracking.firebaseapp.com',
    storageBucket: 'employeetasktracking.firebasestorage.app',
    measurementId: 'G-B7ZWRFM0BP',
  );
}
